### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by exactly-one-kas** [nickbclifford/dotnetdll#1]
Hi,

I'd like to be able to use this excellent crate, but since it has currently no explicit license it is "all rights reserved" by default.

Would you consider assigning a proper license?

**Comment by nickbclifford** [comment]
Thanks for reaching out!

I haven't added a license yet because at first I was waiting until I was ready for a full release, but I'm happy to add one now.

**Comment by nickbclifford** [comment]
Just added in https://github.com/nickbclifford/dotnetdll/commit/0835f279ae8c748568f1259ed89be8da4887b559, thank you for reminding me!
