### ISSUE TITLE
Incorrect writing of generic parameters

### ISSUE THREAD

**Issue by FoLZer** [nickbclifford/dotnetdll#2]
Hey,

I'm not sure if that's a bug in my implementation using your library or it's actually in the library but it seems like [this line](https://github.com/nickbclifford/dotnetdll/blob/c79415cc930a4cfc20bf1aa432a681613f0b944e/src/resolution/write.rs#L395C60-L395C60) should be `build_generic!(t.generic_parameters, TypeDef(idx + 1));` instead in order to skip the <Method> class, as it's done in several other places. 

Without changing the line, it moves every generic parameter up by 1 in dll making them incorrect. (If this is indeed a mistake, it should also affect the security but I've not checked that one yet)

**Comment by nickbclifford** [comment]
Hey, thanks for reaching out! I can indeed reproduce an issue with type generics, so this is definitely dotnetdll's fault - working on a bugfix and test right now.

**Comment by nickbclifford** [comment]
Fixed in https://github.com/nickbclifford/dotnetdll/commit/4a08699e990975951ab08c0bf6ce50d283071209, thanks for bringing this to my attention!
